import {
  err,
  errAsync,
  fromAsyncThrowable,
  fromPromise,
  fromSafePromise,
  fromThrowable,
  ok,
  okAsync,
  type Result,
  ResultAsync,
  safeTry,
} from "neverthrow";

// Re-export neverthrow essentials so consumers don't need dual imports.
// Result instance methods such as map, mapErr, and match remain available on Result values.
export {
  err,
  errAsync,
  fromAsyncThrowable,
  fromPromise,
  fromSafePromise,
  fromThrowable,
  ok,
  okAsync,
  type Result,
  ResultAsync,
  safeTry,
};

/**
 * RFC 9457: Problem Details for HTTP APIs
 * https://www.rfc-editor.org/rfc/rfc9457.html
 *
 * RFC 9457 defines all standard members as optional so that a problem can
 * include only the fields relevant to the response. Unknown extension members
 * are preserved for interoperating with upstream APIs.
 */
export interface ProblemDetails {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
  timestamp?: string;
  [extension: string]: unknown;
}

/**
 * A Problem Details payload generated by this package.
 *
 * Unlike arbitrary RFC 9457 payloads, generated errors always include the
 * standard diagnostic fields and this package's ISO 8601 timestamp extension.
 */
export interface StandardProblemDetails extends ProblemDetails {
  type: string;
  title: string;
  status: number;
  detail: string;
  timestamp: string;
}

/**
 * Standard HTTP error class that creates RFC 9457 compliant error responses
 * wrapped in neverthrow Results.
 *
 * This class maintains a registry of standard HTTP error types and provides
 * methods to create error Results with consistent ProblemDetails formatting.
 *
 * @example
 * ```typescript
 * // Create an error Result
 * return StandardError.getOrDefault(404).error("File not found");
 *
 * // Extract ProblemDetails from Result for logging
 * const result = StandardError.getOrDefault(500).error("Server error");
 * console.error(result.error);
 * ```
 */
export class StandardError {
  /**
   * The HTTP status code for this error type (e.g., 404, 500)
   * @readonly
   */
  readonly status: number;

  /**
   * Human-readable title for this error type (e.g., "Not Found", "Internal Server Error")
   * @readonly
   */
  readonly title: string;

  static #types = new Map<number, StandardError>();

  /**
   * A read-only snapshot of registered error types mapped by status code.
   *
   * Mutating this map cannot affect the shared registry; use `add()` to
   * register or replace an error type intentionally.
   */
  static get types(): ReadonlyMap<number, StandardError> {
    return new Map(StandardError.#types);
  }

  /**
   * Create a new StandardError instance
   *
   * @param status - HTTP status code
   * @param title - Human-readable error title
   */
  constructor(status: number, title: string) {
    this.status = status;
    this.title = title;
    Object.freeze(this);
  }

  /**
   * Register a new error type in the static registry
   *
   * @param status - HTTP status code to register
   * @param title - Human-readable title for this error type
   *
   * @example
   * ```typescript
   * StandardError.add(404, "Not Found");
   * StandardError.add(500, "Internal Server Error");
   * ```
   */
  static add(status: number, title: string) {
    StandardError.#types.set(status, new StandardError(status, title));
  }

  /**
   * Get a registered error type by status code, or default to 500 if not found
   *
   * This method is safe to call with any status code. If the code is not
   * registered, it returns a 500 Internal Server Error instance.
   *
   * @param statusCode - HTTP status code to look up
   * @returns StandardError instance for the given code or 500 default
   *
   * @example
   * ```typescript
   * // Get registered error
   * const notFound = StandardError.getOrDefault(404);
   *
   * // Get unregistered error (returns 500)
   * const teapot = StandardError.getOrDefault(418); // Returns 500 error
   * ```
   */
  static getOrDefault(statusCode: number): StandardError {
    return (
      StandardError.#types.get(statusCode) ??
      StandardError.#types.get(500) ??
      new StandardError(500, "Internal Server Error")
    );
  }

  /**
   * Map HTTP status code to appropriate shell exit code
   *
   * Any error (4xx or 5xx) results in exit code 1, indicating the CLI
   * encountered an error condition that prevented successful completion.
   * Success (2xx) should not use this method.
   *
   * @param statusCode - HTTP status code (unused, always returns 1)
   * @returns Shell exit code 1 for any error
   *
   * @example
   * ```typescript
   * const result = StandardError.getOrDefault(404).error("Not found");
   * if (result.isErr()) {
   *   process.exit(StandardError.toExitCode(result.error.status));
   * }
   * ```
   */
  static toExitCode(_statusCode: number): number {
    return 1;
  }

  /**
   * Get the RFC 9457 type URI for this error
   *
   * Returns a URI reference to httpstatuses.io for the error's status code.
   * This provides a stable, machine-readable identifier for the error type.
   *
   * @returns URI string in format `https://httpstatuses.io/{status}`
   *
   * @example
   * ```typescript
   * const error = StandardError.getOrDefault(404);
   * console.log(error.type); // "https://httpstatuses.io/404"
   * ```
   */
  public get type() {
    return `https://httpstatuses.io/${this.status}`;
  }
  /**
   * Create a Result containing an error with RFC 9457 ProblemDetails
   *
   * This is the primary method for creating error Results in this project.
   * It wraps a ProblemDetails object in a neverthrow Result.err().
   *
   * @param message - Human-readable explanation specific to this error occurrence
   * @param timestamp - Optional ISO 8601 timestamp (defaults to current time if not provided)
   * @param instance - Optional URI reference identifying this specific error occurrence
   * @returns Result.err containing ProblemDetails with all error information
   *
   * @example
   * ```typescript
   * // Basic error
   * return StandardError.getOrDefault(404).error("File not found");
   *
   * // Error with instance URI for tracing
   * return StandardError.getOrDefault(404).error(
   *   "User not found",
   *   undefined,
   *   "/api/users/123"
   * );
   *
   * // Error with custom timestamp
   * const customTime = "2024-01-15T10:30:00.000Z";
   * return StandardError.getOrDefault(500).error("Server error", customTime);
   * ```
   */
  error(
    message: string,
    timestamp?: string,
    instance?: string,
  ): Result<never, StandardProblemDetails> {
    const problemDetails: StandardProblemDetails = {
      type: this.type,
      title: this.title,
      status: this.status,
      detail: message,
      instance: instance,
      timestamp: timestamp ?? new Date().toISOString(),
    };
    return err(problemDetails);
  }
}

// Pre-register every 4xx/5xx status code in the IANA HTTP Status Code
// Registry (https://www.iana.org/assignments/http-status-codes/) so
// downstream clients get a complete starting set rather than only the
// handful this project happened to need first. Titles follow RFC 9110
// where it renamed a reason phrase (e.g. 422 "Unprocessable Content",
// 413 "Content Too Large"). 418 is intentionally omitted: RFC 9110
// §15.5.19 reserves it as "(Unused)" and defines no semantics for it.
StandardError.add(400, "Bad Request");
StandardError.add(401, "Unauthorized");
StandardError.add(402, "Payment Required");
StandardError.add(403, "Forbidden");
StandardError.add(404, "Not Found");
StandardError.add(405, "Method Not Allowed");
StandardError.add(406, "Not Acceptable");
StandardError.add(407, "Proxy Authentication Required");
StandardError.add(408, "Request Timeout");
StandardError.add(409, "Conflict");
StandardError.add(410, "Gone");
StandardError.add(411, "Length Required");
StandardError.add(412, "Precondition Failed");
StandardError.add(413, "Content Too Large");
StandardError.add(414, "URI Too Long");
StandardError.add(415, "Unsupported Media Type");
StandardError.add(416, "Range Not Satisfiable");
StandardError.add(417, "Expectation Failed");
StandardError.add(421, "Misdirected Request");
StandardError.add(422, "Unprocessable Content");
StandardError.add(423, "Locked");
StandardError.add(424, "Failed Dependency");
StandardError.add(425, "Too Early");
StandardError.add(426, "Upgrade Required");
StandardError.add(428, "Precondition Required");
StandardError.add(429, "Too Many Requests");
StandardError.add(431, "Request Header Fields Too Large");
StandardError.add(451, "Unavailable For Legal Reasons");
StandardError.add(500, "Internal Server Error");
StandardError.add(501, "Not Implemented");
StandardError.add(502, "Bad Gateway");
StandardError.add(503, "Service Unavailable");
StandardError.add(504, "Gateway Timeout");
StandardError.add(505, "HTTP Version Not Supported");
StandardError.add(506, "Variant Also Negotiates");
StandardError.add(507, "Insufficient Storage");
StandardError.add(508, "Loop Detected");
StandardError.add(510, "Not Extended");
StandardError.add(511, "Network Authentication Required");

/**
 * Standard shell exit codes
 * https://tldp.org/LDP/abs/html/exitcodes.html
 *
 * For our CLI applications:
 * - Exit with 0 on success
 * - Exit with 1 for any error (4xx or 5xx - prevents shell script continuation)
 *
 * This map documents standard POSIX shell exit codes for reference.
 */
/**
 * A single field-level validation error.
 */
export interface ValidationError {
  field: string;
  reason: string;
  message: string;
}

/**
 * RFC 9457 ProblemDetails extended with a list of field-level validation errors.
 */
export interface ValidationProblemDetails extends ProblemDetails {
  errors: ValidationError[];
}

/**
 * Type guard that checks whether an unknown value conforms to the ProblemDetails shape.
 *
 * @param error - Any unknown value (typically from a catch block)
 * @returns `true` if the value has at least one standard member and every present typed member is valid
 *
 * @example
 * ```typescript
 * try {
 *   await riskyOperation();
 * } catch (e) {
 *   if (isProblemDetails(e)) {
 *     console.error(e.detail); // type-safe access
 *   }
 * }
 * ```
 */
export function isProblemDetails(error: unknown): error is ProblemDetails {
  if (!error || typeof error !== "object") {
    return false;
  }

  const candidate = error as Record<string, unknown>;
  const standardMembers = {
    type: "string",
    title: "string",
    status: "number",
    detail: "string",
    instance: "string",
  } as const;

  let hasStandardMember = false;
  for (const [member, expectedType] of Object.entries(standardMembers)) {
    const value = candidate[member];
    if (value !== undefined) {
      hasStandardMember = true;
      if (typeof value !== expectedType) {
        return false;
      }
    }
  }

  return (
    hasStandardMember &&
    (candidate.timestamp === undefined ||
      typeof candidate.timestamp === "string")
  );
}

/**
 * Extracts a human-readable message from any thrown value.
 *
 * Handles ProblemDetails, Error instances, plain strings, and unknown values,
 * returning a safe fallback for anything else.
 *
 * @param error - Any unknown value (typically from a catch block)
 * @returns The most specific human-readable message available
 *
 * @example
 * ```typescript
 * try {
 *   await riskyOperation();
 * } catch (e) {
 *   console.error(toErrorMessage(e));
 * }
 * ```
 */
export function toErrorMessage(error: unknown): string {
  if (isProblemDetails(error)) {
    return error.detail || error.title || "An unexpected error occurred.";
  }
  if (error instanceof Error) {
    return error.message;
  }
  if (typeof error === "string" && error.length > 0) {
    return error;
  }
  return "An unexpected error occurred.";
}

/**
 * Converts any thrown value into a ProblemDetails object.
 *
 * If the value already is a ProblemDetails it passes through unchanged.
 * Otherwise a new ProblemDetails is created using StandardError for the
 * given status code and the message extracted by toErrorMessage.
 *
 * @param error - Any unknown value (typically from a catch block)
 * @param status - HTTP status code to use when creating a new ProblemDetails (default: 500)
 * @returns A ProblemDetails object
 *
 * @example
 * ```typescript
 * try {
 *   await riskyOperation();
 * } catch (e) {
 *   return err(toProblemDetails(e, 503));
 * }
 * ```
 */
export function toProblemDetails(
  error: unknown,
  status = 500,
  context?: string,
): ProblemDetails {
  if (isProblemDetails(error)) {
    return error;
  }
  const message = context
    ? `${context}: ${toErrorMessage(error)}`
    : toErrorMessage(error);
  const result = StandardError.getOrDefault(status).error(message);
  if (result.isErr()) {
    return result.error;
  }
  throw new Error("Expected StandardError.error to return an error Result.");
}

/**
 * Wraps any thrown value as a neverthrow `err(ProblemDetails)`.
 *
 * Convenience function for early-return patterns in Result-style code.
 * Combines toProblemDetails and err() into a single call.
 *
 * @param error - Any unknown value (typically from a catch block)
 * @param status - HTTP status code to use when creating a new ProblemDetails (default: 500)
 * @returns `Result.err` containing a ProblemDetails
 *
 * @example
 * ```typescript
 * try {
 *   await riskyOperation();
 * } catch (e) {
 *   return problemResult(e, 503);
 * }
 * ```
 */
export function problemResult<T = never>(
  error: unknown,
  status = 500,
  context?: string,
): Result<T, ProblemDetails> {
  return err(toProblemDetails(error, status, context));
}

/**
 * Build a `ProblemDetails` object directly, without going through a `Result`.
 *
 * `StandardError.getOrDefault(status).error(...)` always returns `Err` (its
 * `Ok` type is `never`), so unwrapping it here is safe. This is the
 * unwrapped counterpart to `problemResult` for call sites that just want the
 * `ProblemDetails` value — e.g. to embed as the `error` field of a JSON
 * response, rather than to return as a `Result`.
 *
 * @param status - HTTP status code (looked up via StandardError.getOrDefault)
 * @param message - Human-readable explanation specific to this occurrence
 * @param timestamp - Optional ISO 8601 timestamp (defaults to now)
 * @param instance - Optional URI reference identifying this specific occurrence
 * @returns A complete package-generated `StandardProblemDetails` object (not wrapped in a `Result`)
 *
 * @example
 * ```typescript
 * return { success: false, error: problemDetails(404, "Workspace not found") };
 * ```
 */
export function problemDetails(
  status: number,
  message: string,
  timestamp?: string,
  instance?: string,
): StandardProblemDetails {
  return StandardError.getOrDefault(status)
    .error(message, timestamp, instance)
    ._unsafeUnwrapErr();
}

const DEFAULT_MAX_ERROR_BODY_BYTES = 8 * 1024;
const TRUNCATED_ERROR_BODY_SUFFIX = "… [truncated]";

interface HttpLikeBodyReader {
  read(): Promise<{ done: boolean; value?: Uint8Array }>;
  cancel(reason?: unknown): Promise<void>;
}

/**
 * Minimal shape shared by the Web Fetch API `Response` and other
 * fetch-like response types (e.g. platform-specific `fetch` wrappers),
 * covering the methods needed to validate and read an HTTP response.
 */
export interface HttpLikeResponse {
  ok: boolean;
  status: number;
  statusText: string;
  body?: { getReader(): HttpLikeBodyReader } | null;
  text(): Promise<string>;
}

/**
 * Controls how much upstream error-body content can be included in a
 * generated Problem Details response.
 */
export interface ValidateHttpResponseOptions {
  /** Maximum UTF-8 bytes retained from an upstream error body. Defaults to 8 KiB. */
  maxErrorBodyBytes?: number;
}

function truncateErrorBody(text: string, maxBytes: number): string {
  const encoder = new TextEncoder();
  let truncated = "";
  let bytes = 0;

  for (const character of text) {
    const characterBytes = encoder.encode(character).byteLength;
    if (bytes + characterBytes > maxBytes) {
      return `${truncated}${TRUNCATED_ERROR_BODY_SUFFIX}`;
    }
    truncated += character;
    bytes += characterBytes;
  }

  return truncated;
}

async function cancelReader(reader: HttpLikeBodyReader): Promise<void> {
  try {
    await reader.cancel();
  } catch {
    // A failed cancellation must not replace the original upstream response.
  }
}

async function readBoundedErrorBody(
  response: HttpLikeResponse,
  maxBytes: number,
): Promise<string> {
  if (!response.body) {
    return truncateErrorBody(await response.text(), maxBytes);
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let body = "";
  let bytesRead = 0;

  while (true) {
    const chunk = await reader.read();
    if (chunk.done) {
      return body + decoder.decode();
    }

    const value = chunk.value;
    if (!value || value.byteLength === 0) {
      continue;
    }

    const remainingBytes = maxBytes - bytesRead;
    if (value.byteLength > remainingBytes) {
      body += decoder.decode(value.subarray(0, remainingBytes), {
        stream: true,
      });
      body += decoder.decode();
      await cancelReader(reader);
      return `${body}${TRUNCATED_ERROR_BODY_SUFFIX}`;
    }

    body += decoder.decode(value, { stream: true });
    bytesRead += value.byteLength;

    if (bytesRead === maxBytes) {
      const nextChunk = await reader.read();
      if (nextChunk.done) {
        return body + decoder.decode();
      }

      body += decoder.decode();
      await cancelReader(reader);
      return `${body}${TRUNCATED_ERROR_BODY_SUFFIX}`;
    }
  }
}

function getMaxErrorBodyBytes(options: ValidateHttpResponseOptions): number {
  const maxBytes = options.maxErrorBodyBytes ?? DEFAULT_MAX_ERROR_BODY_BYTES;
  if (!Number.isSafeInteger(maxBytes) || maxBytes < 1) {
    throw new RangeError("maxErrorBodyBytes must be a positive safe integer");
  }
  return maxBytes;
}

/**
 * Validate an HTTP response and convert a non-ok response into a
 * `ResultAsync` error, using `Result` instead of throwing.
 *
 * A readable body is consumed only up to `maxErrorBodyBytes` and then cancelled.
 * Text-only response wrappers cannot be read incrementally, so their emitted error
 * detail is capped after reading completes.
 *
 * @param response - Any fetch-like response object
 * @param context - Short description of the operation for the error message
 * @param status - Status code to use if reading the error body itself fails (default: 502)
 * @param options - Error-body retention options
 * @returns `ResultAsync` resolving to `ok(response)` if `response.ok`, or `err(ProblemDetails)` otherwise
 */
export function validateHttpResponse<T extends HttpLikeResponse>(
  response: T,
  context: string,
  status = 502,
  options: ValidateHttpResponseOptions = {},
): ResultAsync<T, ProblemDetails> {
  if (response.ok) {
    return okAsync(response);
  }

  const maxErrorBodyBytes = getMaxErrorBodyBytes(options);
  return fromPromise(readBoundedErrorBody(response, maxErrorBodyBytes), (e) =>
    toProblemDetails(e, status),
  ).andThen((errorText) =>
    errAsync(
      new StandardError(response.status, response.statusText)
        .error(
          `Failed to ${context}: ${response.status} ${response.statusText} - ${errorText}`,
        )
        ._unsafeUnwrapErr(),
    ),
  );
}

export const ShellExitCodes = new Map<number, string>([
  [0, "Success"],
  [1, "Catchall for general errors"],
  [2, "Misuse of shell builtins"],
  [126, "Command invoked cannot execute"],
  [127, "Command not found"],
  [128, "Invalid argument to exit"],
  [130, "Script terminated by Control-C"],
  // 128+n, Fatal error signal "n": $PPID of script returns 137 (128 + 9)
  // 255*, Exit status out of range: exit takes only integer args in the range 0 - 255
]);
